# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:     ["tables"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mateusz Zatorski
tagline:          'Blog'
url:              http://zatorski.co
shorturl:         zatorski.co

baseurl:          /

author:
  name:           Mateusz Zatorski
  url:            https://twitter.com/matzatorski
  email:          mateuszzatorski@gmail.com

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/knowbody/knowbody.github.io

# This is the list of pages to include in the header
pages_list:
  about:          '/about'
  projects:       '/projects'
  archive:        '/archive'
  github:         'https://github.com/knowbody'
  twitter:        'https://twitter.com/matzatorski'


# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
